services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - redis
  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
