bot_token: token
chat_id: 123123123
dsn: bot.db
interval: 3h
auto_delete_days: 30
notify_since: 9
notify_to: 19
webhook_server: "http://myserver.com"          
server_port: 8888           
bot_mode" env: polling
redis_host: "localhost"
redis_port: "6379"
redis_password: ""
redis_db: 0
fsm_timeout: "10m"